@startuml
'https://plantuml.com/class-diagram

class Etablissement {
    - nom : string
    - slug : string
    - description : string
    - numeroTelephone : string
    - adressePostale : string
    - ville : Ville
    - adresseEmail : string
    - image : string
    - estActif : bool
    - estSurAccueil : bool
    - createdAt : DateTime
    - updatedAt : DateTime
}

class Ville {

    - nom : string
    - codePostal : string
    - nomDepartement : string
    - numeroDepartement : string
    - nomRegion : string

}

class Categorie {

    - nom : string
    - createdAt : DateTime

}

class Utilisateur {

    - prenom : string
    - nom : string
    - pseudo : string
    - adresseEmail : string
    - motDePasse : string
    - createdAt : DateTime
    - updatedAt : DateTime
    - roles : array
    - estActif : bool

}

Ville "1  " ---> "0..*  " Etablissement
Categorie "1..*" ---> "0..*" Etablissement


@enduml